/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/assets/chess.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/chess.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 1.5, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.materials1.geometry} material={materials.m010} />
        <mesh geometry={nodes.materials1_1.geometry} material={materials.m007} />
        <mesh geometry={nodes.materials1_2.geometry} material={materials.n} />
        <mesh geometry={nodes.materials1_3.geometry} material={materials.m011} />
      </group>
      <group position={[0, 0.9, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.materials2.geometry} material={materials.m001} />
        <mesh geometry={nodes.materials2_1.geometry} material={materials.m002} />
        <mesh geometry={nodes.materials2_2.geometry} material={materials.n001} />
        <mesh geometry={nodes.materials2_3.geometry} material={materials.n003} />
      </group>
      <group position={[0, 0.57, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.materials3.geometry} material={materials.m004} />
        <mesh geometry={nodes.materials3_1.geometry} material={materials.m005} />
        <mesh geometry={nodes.materials3_2.geometry} material={materials.m006} />
        <mesh geometry={nodes.materials3_3.geometry} material={materials.n002} />
      </group>
    </group>
  )
}

useGLTF.preload('/chess.glb')
